"""phase2_model_upgrades_payment_order_user

Revision ID: 3fb3fd862589
Revises: 82ed4444bf8e
Create Date: 2026-04-25 18:21:08.175359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb3fd862589'
down_revision: Union[str, Sequence[str], None] = '82ed4444bf8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('razorpay_refund_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_refunded', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('state', sa.Enum('created', 'attempted', 'authorized', 'captured', 'failed', 'refund_initiated', 'refunded', 'partially_refunded', name='payment_state_enum'), nullable=False),
    sa.Column('method', sa.Enum('razorpay', 'upi', 'card', 'netbanking', 'wallet', 'cod', name='payment_method_enum'), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_razorpay_refund_id'), 'payments', ['razorpay_refund_id'], unique=False)
    op.create_index('ix_payments_state', 'payments', ['state'], unique=False)
    op.create_index('ix_access_logs_created_at', 'access_logs', ['created_at'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_access_logs_ip_address'), 'access_logs', ['ip_address'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False, if_not_exists=True)
    op.add_column('order_items', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('product_category', sa.String(length=100), nullable=True))
    op.add_column('order_items', sa.Column('print_specs', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('custom_specs', sa.JSON(), nullable=True))
    op.add_column('order_items', sa.Column('special_instructions', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=50), nullable=True))
    op.add_column('orders', sa.Column('coupon_discount', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0')))
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_city', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_state', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_postal_code', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('delivery_notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index('ix_orders_razorpay', 'orders', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=False)
    op.add_column('reviews', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('flagged_reason', sa.String(length=500), nullable=True))
    op.add_column('reviews', sa.Column('moderated_by', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('moderated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_moderated_by_users'), 'reviews', 'users', ['moderated_by'], ['id'])
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.create_index('ix_roles_slug', 'roles', ['slug'], unique=False)
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('admin_notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'admin_notes')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'gst_number')
    op.drop_column('users', 'notification_preferences')
    op.drop_index('ix_roles_slug', table_name='roles')
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.drop_constraint(op.f('fk_reviews_moderated_by_users'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'moderated_at')
    op.drop_column('reviews', 'moderated_by')
    op.drop_column('reviews', 'flagged_reason')
    op.drop_column('reviews', 'is_flagged')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_index('ix_orders_razorpay', table_name='orders')
    op.drop_column('orders', 'is_deleted')
    op.drop_column('orders', 'razorpay_order_id')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'confirmed_at')
    op.drop_column('orders', 'admin_notes')
    op.drop_column('orders', 'delivery_notes')
    op.drop_column('orders', 'delivery_postal_code')
    op.drop_column('orders', 'delivery_state')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'coupon_discount')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('order_items', 'special_instructions')
    op.drop_column('order_items', 'custom_specs')
    op.drop_column('order_items', 'print_specs')
    op.drop_column('order_items', 'product_category')
    op.drop_column('order_items', 'product_name')
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_ip_address'), table_name='access_logs')
    op.drop_index('ix_access_logs_created_at', table_name='access_logs')
    op.drop_index('ix_payments_state', table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_refund_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
