"""migrate user role enum and hashed_password

Revision ID: 7b81bafe0fbc
Revises: 93c5f7325ceb
Create Date: 2026-02-26 22:49:45.171316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b81bafe0fbc'
down_revision: Union[str, Sequence[str], None] = '93c5f7325ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_paid_at'), table_name='orders', postgresql_where="(payment_status = 'paid'::payment_status_enum)")
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # convert existing role values to enum by casting; PostgreSQL requires USING
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE user_role_enum USING role::user_role_enum")
    # reflect the new type to Alembic's API (above execute handles conversion)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ADMIN', 'CUSTOMER', name='user_role_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'CUSTOMER', name='user_role_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'hashed_password')
    op.create_index(op.f('ix_orders_paid_at'), 'orders', ['paid_at'], unique=False, postgresql_where="(payment_status = 'paid'::payment_status_enum)")
    # ### end Alembic commands ###
