"""add_description_unit_image_to_products

Revision ID: cfb8f6b4d6d0
Revises: 91f3eb4bcc4a
Create Date: 2026-03-07 15:28:52.124442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfb8f6b4d6d0'
down_revision: Union[str, Sequence[str], None] = '91f3eb4bcc4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission_access_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_permission_access_logs_permission_id'), table_name='permission_access_logs')
    op.drop_index(op.f('ix_permission_access_logs_resource'), table_name='permission_access_logs')
    op.create_index('ix_access_logs_created_at', 'permission_access_logs', ['created_at'], unique=False)
    op.create_index('ix_access_logs_permission_id', 'permission_access_logs', ['permission_id'], unique=False)
    op.create_index('ix_access_logs_resource', 'permission_access_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_access_logs_user_id', 'permission_access_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_permission_access_logs_resource_type'), 'permission_access_logs', ['resource_type'], unique=False)
    op.drop_constraint(op.f('fk_permission_access_logs_permission_id_permissions'), 'permission_access_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_permission_access_logs_permission_id_permissions'), 'permission_access_logs', 'permissions', ['permission_id'], ['id'])
    op.alter_column('permissions', 'is_dangerous',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('permissions', 'is_delegable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('uq_permissions_permission_key'), 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_is_active'), 'permissions', ['is_active'], unique=False)
    op.create_index(op.f('ix_permissions_permission_key'), 'permissions', ['permission_key'], unique=True)
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('role_assignment_logs', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_role_assignment_logs_action'), 'role_assignment_logs', ['action'], unique=False)
    op.create_index(op.f('ix_role_assignment_logs_created_at'), 'role_assignment_logs', ['created_at'], unique=False)
    op.drop_constraint(op.f('fk_role_assignment_logs_approved_by_id_users'), 'role_assignment_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_assignment_logs_assigned_by_id_users'), 'role_assignment_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_assignment_logs_approved_by_id_users'), 'role_assignment_logs', 'users', ['approved_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_role_assignment_logs_assigned_by_id_users'), 'role_assignment_logs', 'users', ['assigned_by_id'], ['id'])
    op.alter_column('roles', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('roles', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('roles', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.drop_constraint(op.f('uq_roles_slug'), 'roles', type_='unique')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_constraint(op.f('fk_roles_parent_role_id_roles'), 'roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_roles_created_by_users'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roles_parent_role_id_roles'), 'roles', 'roles', ['parent_role_id'], ['id'])
    op.create_foreign_key(op.f('fk_roles_created_by_users'), 'roles', 'users', ['created_by'], ['id'])
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('fk_user_roles_assigned_by_users'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_assigned_by_users'), 'user_roles', 'users', ['assigned_by'], ['id'])
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'mfa_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_user_roles_assigned_by_users'), 'user_roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_roles_assigned_by_users'), 'user_roles', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.alter_column('user_roles', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('fk_roles_created_by_users'), 'roles', type_='foreignkey')
    op.drop_constraint(op.f('fk_roles_parent_role_id_roles'), 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_roles_created_by_users'), 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_roles_parent_role_id_roles'), 'roles', 'roles', ['parent_role_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_roles_slug'), 'roles', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('roles', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('roles', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('roles', 'is_system_role',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_role_assignment_logs_assigned_by_id_users'), 'role_assignment_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_role_assignment_logs_approved_by_id_users'), 'role_assignment_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_role_assignment_logs_assigned_by_id_users'), 'role_assignment_logs', 'users', ['assigned_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_role_assignment_logs_approved_by_id_users'), 'role_assignment_logs', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_role_assignment_logs_created_at'), table_name='role_assignment_logs')
    op.drop_index(op.f('ix_role_assignment_logs_action'), table_name='role_assignment_logs')
    op.alter_column('role_assignment_logs', 'requires_approval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'description')
    op.drop_index(op.f('ix_permissions_permission_key'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_is_active'), table_name='permissions')
    op.create_unique_constraint(op.f('uq_permissions_permission_key'), 'permissions', ['permission_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('permissions', 'is_delegable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('permissions', 'is_dangerous',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('fk_permission_access_logs_permission_id_permissions'), 'permission_access_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_permission_access_logs_permission_id_permissions'), 'permission_access_logs', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_permission_access_logs_resource_type'), table_name='permission_access_logs')
    op.drop_index('ix_access_logs_user_id', table_name='permission_access_logs')
    op.drop_index('ix_access_logs_resource', table_name='permission_access_logs')
    op.drop_index('ix_access_logs_permission_id', table_name='permission_access_logs')
    op.drop_index('ix_access_logs_created_at', table_name='permission_access_logs')
    op.create_index(op.f('ix_permission_access_logs_resource'), 'permission_access_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_permission_access_logs_permission_id'), 'permission_access_logs', ['permission_id'], unique=False)
    op.alter_column('permission_access_logs', 'success',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
