"""describe change

Revision ID: ede84ebd5e1e
Revises: c7295d7f80f0
Create Date: 2026-02-26 18:31:23.581347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede84ebd5e1e'
down_revision: Union[str, Sequence[str], None] = 'c7295d7f80f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extra_rates', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('material_rates', 'rate_per_sqft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'width_ft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('order_items', 'height_ft',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('order_items', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.drop_constraint(op.f('fk_order_items_order_id_orders'), 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_items_order_id_orders'), 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('email', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('password', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('role', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_orders_user_email'), table_name='orders')
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=True)
    op.create_index(op.f('ix_orders_reset_token'), 'orders', ['reset_token'], unique=False)
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'user_email')
    op.drop_column('orders', 'total_price')
    op.alter_column('products', 'base_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.alter_column('products', 'base_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.add_column('orders', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_reset_token'), table_name='orders')
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.create_index(op.f('ix_orders_user_email'), 'orders', ['user_email'], unique=False)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'reset_token_expiry')
    op.drop_column('orders', 'reset_token')
    op.drop_column('orders', 'role')
    op.drop_column('orders', 'password')
    op.drop_column('orders', 'email')
    op.drop_constraint(op.f('fk_order_items_order_id_orders'), 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_items_order_id_orders'), 'order_items', 'orders', ['order_id'], ['id'])
    op.alter_column('order_items', 'total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'height_ft',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('order_items', 'width_ft',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('material_rates', 'rate_per_sqft',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('extra_rates', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
