"""fix corrupted order model

Revision ID: f3061cbd3567
Revises: ede84ebd5e1e
Create Date: 2026-02-26 18:32:50.636631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3061cbd3567'
down_revision: Union[str, Sequence[str], None] = 'ede84ebd5e1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False))
    op.drop_index(op.f('ix_orders_email'), table_name='orders')
    op.drop_index(op.f('ix_orders_reset_token'), table_name='orders')
    op.create_foreign_key(op.f('fk_orders_user_id_users'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'role')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'password')
    op.drop_column('orders', 'reset_token_expiry')
    op.drop_column('orders', 'reset_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('reset_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_orders_user_id_users'), 'orders', type_='foreignkey')
    op.create_index(op.f('ix_orders_reset_token'), 'orders', ['reset_token'], unique=False)
    op.create_index(op.f('ix_orders_email'), 'orders', ['email'], unique=True)
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
